# Generated by Django 6.0.3 on 2026-04-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
